version: '3'
services:
  app-order:
    container_name: app-order
    image: 34234247632/order-service:v2.0
    networks:
      - otus-msa-hw8
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    environment:
      DB_HOST: db
      DB_PASSWORD: example
  app-storage:
    container_name: app-storage
    image: 34234247632/storage-service:v1.0
    networks:
      - otus-msa-hw8
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8001"
    depends_on:
      - "app-order"
    environment:
      DB_HOST: db
      DB_PASSWORD: example
  app-delivery:
    container_name: app-delivery
    image: 34234247632/delivery-service:v1.0
    networks:
      - otus-msa-hw8
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8002"
    depends_on:
      - "app-storage"
    environment:
      DB_HOST: db
      DB_PASSWORD: example
  app-payment:
    container_name: app-payment
    image: 34234247632/payment-service:v1.0
    networks:
      - otus-msa-hw8
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8003"
    depends_on:
      - "app-delivery"
    environment:
      DB_HOST: db
      DB_PASSWORD: example
  db:
    container_name: db
    image: postgres:14.4
    restart: always
    networks:
      - otus-msa-hw8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      TZ: 'Europe/Moscow'

networks:
  otus-msa-hw8:
